from app.analyzers.keywords.candidate_tokens_extractor.pos_candidate_token_extractor_module import \
    PosCandidateTokenExtractorModule
from app.analyzers.keywords.keyword_builders.pos_keyword_builder_module import PosKeywordBuilderModule
